name: Build `vibe` & `vibed`

on:
  push:
    branches: [ "release" ]
  pull_request:
    branches: [ "release" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build `vibe` & `vibed`
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'macos-latest' # for Arm based macs (M1 and above).
            args: '--target aarch64-apple-darwin'
          - platform: 'macos-latest' # for Intel based macs.
            args: '--target x86_64-apple-darwin'
          - platform: 'ubuntu-22.04' # for Tauri v1 you could replace this with ubuntu-20.04.
            args: ''
          - platform: 'windows-latest'
            args: ''

    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install Rust Stable
        uses: dtolnay/rust-toolchain@stable
        with:
          # Those targets are only used on macos runners so it's in an `if` to slightly speed up windows and linux builds.
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - name: Install Dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-22.04' # This must match the platform value defined above.
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.0-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf
        # webkitgtk 4.0 is for Tauri v1 - webkitgtk 4.1 is for Tauri v2.
        # You can remove the one that doesn't apply to your app to speed up the workflow a bit.

      - name: Install Frontend Dependencies
        working-directory: vibe
        run: bun install

      - name: Build Frontend `vibe`
        working-directory: vibe
        run: bun run tauri build

      - name: Build Backend `vibed`
        working-directory: vibed
        run: cargo build --release
        
      - name: Upload Frontend Artifact `vibe`
        uses: actions/upload-artifact@v4
        with:
          name: frontend-${{ matrix.os }}
          path: vibe/src-tauri/target/release/bundle/

      - name: Upload Backend Artifact `vibed`
        uses: actions/upload-artifact@v4
        with:
          name: backend-${{ matrix.os }}
          path: vibed/target/release/vibed*
